SQLZ>
	(Table)
		(column1(type=DataTypes.STRING))
		($if (false))
			(column2(type=DataTypes.STRING))
		(...columns)
			(column3(type=DataTypes.STRING))
			($if (100 == 100))
				(column4(type=DataTypes.STRING))
					($if (true))
						(unique=true)
		(...options)
			($if (true))
				(someTableOption)
					(key=val)
					($if (false))
						(someOtherOption=true)
		(...associations)
			($if (yo))
				(hasMany.OtherThings)
				(hasOne.Stuff)
				($if (secondyo))
					(Steps=hasOne.Step)
			($elseif (yoelse))
				(hasMany.Yo)
			($else)
				(hasOne.Yos)
			(Things=hasMany.Things)
				($if (insideThings))
					(as='conditionalAs')
			(hasMany.OtherThings)
				(attrib='1234')
				($if (insideOtherThings))
					(as='conditionalAs')
			($if (true))
				(hasMany.OtherThings)
