SQLZ>
	(Table)
		(...columns)
			(column1(type=DataTypes.STRING))
			//($if (false))
				//(column2(type=DataTypes.STRING))
		(...options)
			//($if (false))
				//(plural='alksd')
		(...associations)
			($if (yo))
				(hasMany.OtherThings)
				(hasOne.Stuff)
				($if (secondyo))
					(Steps=hasOne.Step)
			($elseif (yoelse))
				(hasMany.Yo)
			($else)
				(hasOne.Yos)
			(Things=hasMany.Things)
				($if (insideThings))
					(as='conditionalAs')
			(hasMany.OtherThings)
				(attrib='1234')
				($if (insideOtherThings))
					(as='conditionalAs')
			($if (true))
				(hasMany.OtherThings)
